#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Mar 15 11:41:19 2018

@author: Charlie
"""

def isIn (char, aStr):
    '''
    char: a single character
    aStr: an alphabetized string
    
    returns: True if char is in aStr; False otherwise
    '''
    
    
    #base cases
    
    if len(aStr) == 0:
        return False
        print (("Character is not in string."))
    
    
    elif len(aStr) == 1:
        
        if char == aStr:
            return True 
            (print ("Character is in string;"))
            
        return False
        (print ("Character is not in string."))
                                              
    
    middleLetter = aStr[len(aStr)//2]                   # redefine middle letter
    
   
    if char == middleLetter:
        return True
        (print ("Character is in string."))
    
    
    # recursive calls
    
    elif char < middleLetter:                           # char is lower than middle letter
        aStr = aStr[:aStr.index (middleLetter)]         # cut aStr above char
        isIn (char, aStr)                               # recurse to isIn
        
        
    else:
        aStr = aStr[aStr.index (middleLetter):]         # cut string below middle letter
        isIn (char, aStr)                               # recurse to isIn
        
 
        
        
        
        
        
        
        