#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Apr  6 16:04:00 2018

@author: ElAwbery
"""


def playGame(wordList):
    """
    Allow the user to play an arbitrary number of hands.

    1) Asks the user to input 'n' or 'r' or 'e'.
      * If the user inputs 'n', let the user play a new (random) hand.
      * If the user inputs 'r', let the user play the last hand again.
      * If the user inputs 'e', exit the game.
      * If the user inputs anything else, tell them their input was invalid.
 
    2) When done playing the hand, repeat from step 1    
    """
    #This code does not work:
    
    
    theHand = {}
    
    while (True):
        
        userInput = input("Enter n to deal a new hand, r to replay the last hand, or e to end game:")
        
        if userInput =='e':
            return
        
        if userInput == 'n' or userInput == 'r':
           
            while (True):
                
                # user game or computer game? 
                secondInput = input ("Enter u to have yourself play, c to have the computer play:")
            
                if secondInput != 'u' and secondInput != 'c':
                    print("Invalid command.")
                    True
        
                elif userInput =='n':
                    theHand = dealHand(HAND_SIZE)
                    
                    if secondInput == 'u':
                        playHand(theHand, wordList, HAND_SIZE)
                        
                    else:
                        compPlayHand(theHand, wordList, HAND_SIZE)
                        break
                    
                else: #userInput == 'r'
                    
                    if theHand != {}:
                        
                        if secondInput == 'u':
                            playHand(theHand, wordList, HAND_SIZE)
                        
                        else:
                            compPlayHand(theHand, wordList, HAND_SIZE)
                        
                    else:
                        print("You have not played a hand yet. Please play a new hand first!")
                    
        else:
            print("Invalid command.")
        True
        
        
        
        
            
            
    
  
