#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 29 13:28:34 2018

@author: ElAwbery
"""

import pylab as plt

sampleList = []
sampleLinear = []
sampleQuadratic = []
sampleCubic = []
sampleExponential = []

for i in range (0,30):
    sampleList.append(i)
    sampleLinear.append(i)
    sampleQuadratic.append(i**2)
    sampleCubic.append(i**3)
    sampleExponential.append(1.5**i)
    
plt.figure('cubic')
plt.plot(sampleList, sampleCubic)
plt.figure('expo')
plt.plot(sampleList, sampleExponential)
plt.figure('linear')
plt.plot(sampleList, sampleLinear)
plt.figure('quadratic')
plt.plot(sampleList, sampleQuadratic)

plt.xlabel('mysamples')







            
