#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar 25 14:33:11 2018

@author: ElAwbery
"""
'''
Exhaustive enumeration approach to finding a square root
'''

x = 0.25
epsilon = 0.01
step = epsilon**2
numGuesses = 0
ans = 1.0
while abs(ans**2 - x) >= epsilon and ans >= x:
    ans = ans - step
    numGuesses += 1
print ("numGuesses =", numGuesses)

if abs(ans**2 - x) >= epsilon:
    print ("failed on square root of:", x)
else:
    print (ans, "is close to square root of", x)
    
    # The step is the same every time, and it is minute
    # The last value before ans^2 exceeds x is too small and the one after that is too big
    # So the condition that stops the program running is that the variable ans^2 exceeds the size of x
   
