#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed May  9 10:18:49 2018

@author: Charlie
"""

def generator1():
    if True:
        print('hi')
        yield 3 

def generator2():
    if False:   
        yield 1

g1 = generator1()
g2 = generator2()

'''
print(type(g1))
print(type(g2))
print(next(g1))
print(next(g2))
'''